export const API_URL = 'https://painfx.onrender.com/api';

export const ENDPOINTS = {
  LOGIN: "/jwt/create/",
  GOOGLE_LOGIN: "/o/google/",
  LOGOUT: "/logout/",
  WS_URL : 'painfx.onrender.com',
  TOKEN_REFRESH: "/jwt/refresh/",
  USER_PROFILE: "/users/me/",
  USER: "/users/",
  DOCTORS: "/doctors/",
  CLINICS: "/clinics/",
  PATIENTS: "/patients/",
  CLINICS_DETAIL: "/posts/{id}/",
  PATIENTS_DETAIL: "/posts/{id}/",
  RESERVATIONS: "/reservations/",
  REVIEWS: "/reviews/",
  POSTS: "/posts/",
  COMMENTS: "/comments/",
  LIKES: "/likes/",
  LIKE_UNLIKE: "/likes/{id}/unlike/",
  POST_DETAIL: "/posts/{id}/",
  POST_INCREMENT_VIEW_COUNT: "/posts/{id}/increment_view_count/",
  POST_ADD_TAGS: "/posts/{id}/add_tags/",
  POST_LIKES: "/posts/{id}/likes/",
  POST_COMMENTS: "/posts/{id}/comments/",
  COMMENT_DETAIL: "/comments/{id}/",
  COMMENT_REPLY: "/comments/{id}/reply/",
  CATEGORIES: "/categories/",
  SUBSCRIPTIONS: "/subscriptions/",
  PAYMENT_METHODS: "/payment-methods/",
  PAYMENTS: "/payments/",
  NOTIFICATIONS: "/notifications/",
  EVENT_SCHEDULES: "/event-schedules/",
  ADVERTISING_CAMPAIGNS: "/advertising-campaigns/",
  USERS_AUDIT:"/users-audit/",
  STRIPE_WEBHOOK:"/webhooks/stripe/",
};